// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pozbctftgurybmlweaxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvemJjdGZ0Z3VyeWJtbHdlYXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDExNzQsImV4cCI6MjA3NDA3NzE3NH0.Ky5yktWtXuBqM3SIwsipcdt1xYZFcEBBPxU8S5qYHd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});